services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=prod
      - MESSENGER_TRANSPORT_DSN=redis://redis:6379/messages
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    healthcheck:
      test: [ "CMD-SHELL", "php -v || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
  redis:
    image: redis:alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
